### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yucombinator** [icechen1/l33t#1]
- [x] Load Website
- [x] Click start game
- [x] generates a new lobby and shows user a link (share this link to add other players to the game)
- [x] link has lobby id appended to it
- [x] enter game. layout is hackertyper scrolling code ui with balance bar on top and player roster on the right
- [x] client side sends key presses per second every second to server over socket.io
- [ ] add voice chat with entire team

Ideas:
- [x] Random space team style events on random teammate screen and actionable event on another screen.
- [ ] Interns?
- [ ] Versus mode
- [ ] More patterns to type
- [ ] DDR in shortcut area
- [ ] Combine elements into attack items

**Comment by icechen1** [comment]
Also fix: if someone disconnects remove his or her events
